### ISSUE TITLE
Bad system call when running on termux using epoll

### ISSUE THREAD

**Issue by Kayden1412** [mookums/zzz#12]
When trying to access the server it will get terminated.

![Screenshot_2024-11-14-15-56-25-60_84d3000e3f4017145260f7618db1d683](https://github.com/user-attachments/assets/11580387-dc61-4a86-a679-aabf9a0b7ea2)

![Screenshot_2024-11-14-16-02-22-86_84d3000e3f4017145260f7618db1d683](https://github.com/user-attachments/assets/ae209693-7df7-4fe6-babb-cf414a6b3a52)

Strace output
https://gist.github.com/Kayden1412/d1837c89c73b139eac7bc8d1b5a065b3

zzz version 0.2

**Comment by mookums** [comment]
Seems like you're running into an issue where [seccomp](https://man7.org/linux/man-pages/man2/seccomp.2.html) is blocking the accept call.  I've never used termux so I'm not 100% sure but you could try disabling seccomp and it should work.
