### ISSUE TITLE
How to use pg.zig with zzz?

### ISSUE THREAD

**Issue by Kayden1412** [mookums/zzz#15]
https://github.com/karlseguin/pg.zig

**Comment by Smithx10** [comment]
I too am attempting to do this.

**Comment by mookums** [comment]
Hi you two (@Kayden1412 & @Smithx10), I put together a gist that utilizes pg.zig on the current main branch of zzz [here](https://gist.github.com/mookums/8c30a40ac7de4480dcee17fd298b02d7). I'll probably end up adding it as an example on the next release. 

With regards to the gist exmaple, you either send a GET to "/" to get a page with all of the items or you send a POST to "/" with a name query (eg. localhost:9862?name="muki") and it'll generate a random id.

The most important thing to note is that pg.zig is blocking so while your handler is accessing the database, that thread will be blocked. You should expect a pretty large performance hit from this. Ideally, the database drivers should also use the Tardy runtime (allowing for concurrent handling) but I haven't gotten around to making one yet.
